name: build

runs:
  using: composite

  steps:
    - name: Setup JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: 17
        cache: 'gradle'

    - name: Generate signing key
      shell: bash
      run: |
        keytool -genkey -v \
          -keystore keystore.jks \
          -alias app \
          -keyalg RSA \
          -keysize 2048 \
          -validity 10000 \
          -storepass password \
          -keypass password \
          -dname "CN=App"

    - name: Build with Gradle
      shell: bash
      run: ./gradlew assembleDebug

    - name: Generate Android.bp
      shell: bash
      run: |
        ./gradlew app:generateBp
        if [[ ! -z $(git status -s) ]]; then
          git status
          exit -1
        fi

    - uses: actions/upload-artifact@v4
      with:
        name: app-debug.apk
        path: app/build/outputs/apk/debug/app-debug.apk
